// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $examples_joke from "./routes/examples/joke.tsx";
import * as $examples_outlines_name_ from "./routes/examples/outlines/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $Joke from "./islands/Joke.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/examples/joke.tsx": $examples_joke,
    "./routes/examples/outlines/[name].tsx": $examples_outlines_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/signup.tsx": $signup,
  },
  islands: {
    "./islands/Joke.tsx": $Joke,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
